package.json, yarn.lock
While we were waiting for merge of PR #9, four more patch versions were released. Let's update to the latest.
=> Update file-loader to the latest version 1.1.4 🚀

.codeclimate.yml
- Put all plugins under `plugins` node (remove deprecated and redundant `engines` node)
- Rename `exclude_paths` to `exclude_patterns` (`exclude_paths` is deprecated)
- The `engines` and `plugins` node provide the same functionality
- `engines` is now deprecated`
- Using `engines` and `plugins` together will break the analysis
- `exclude_paths` is deprecated
- I forked the repo and added it to Code Climate
- Made these changes on my fork
- Got a successful analysis
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Update deprecated `engines` and `exclude_paths`

src/gfx/shaders/Uber_frag.glsl
Correct the color of sprites for flat material in the fog.
Has been tested by npm run ci test
=> Fix fog interpolation for sprites

src/Miew.js, src/gfx/Representation.js, src/gfx/shaders/UberMaterial.js, src/gfx/shaders/Uber_frag.glsl, src/settings.js
Added fogAlpha to make a part of molecule behind fogFarFactor colored by fogColor * fogAlpha. It's possible to change fogAlpha using terminal.
FogAlpa is a new feature.
Tests e2e were passed.
=> Add fogAlpha

src/gfx/gfxutils.js
Exclude extra defines for materials in PREPASS_TRANSPARENT layer
This change makes uberfragmentShader shorter for rendering objects from PREPASS_TRANSPARENT layer and as result quicker. It also prevents some errors that may occur when shader changes.
e2e tests passed
=> Fix transparent

src/gfx/materials.js
Solve problem: "Backdrop material works inconsistently"
This change solves follow problem: 
"Backdrop material works inconsistently", v0.7.19, "Open miew with 1CRN by default, change the second representation to Quick Surface, Backdrop Material (and "all" selector). It hides the first representation. Expected: it serves as a backdrop."
e2e tests passed
=> fix backdrop material

src/Miew.js
Molecule disappers when SSAO-on and FXAA-off at the same time. This change solve it.
=> Fix molecule disappering when SSAO-on and FXAA-off at the same time

src/Miew.js, src/gfx/Representation.js, src/gfx/gfxutils.js
These changes solve the problem with recompiling pixel material shader on each frame when volume and molecules are represented at the same time. This problem is demonstrated in dramatically decreased fps with simultaneous representation volume and molecules.
To avoid recompiling shaders on each frame there are creating once on building stage "color from position" meshes, these meshes are cloned from origin meshes. And then these meshes are used on each frame for creating texture with distance to molecules.
=> Fixed decreased performance bug with simultaneous representation volume and molecules 

src/Miew.js
Initialize gfx.renderer.shadowMap using the value of settings.now.shadow.on
=> Fix initializing gfx.renderer.shadowMap

src/gfx/geometries/ExtrudedObjectsGeometry.js, src/gfx/modes/groups/ResiduesSubseqGroup.js, src/settings.js
- Fix normals counting for Cartoon mode;
- Rotate base shape for Cartoon and Tube modes (for having points on angles of arrows in Cartoon mode);
- Change value of PolyComplexity.poor for:
- BallsandSticks mode because three points give a much better result than two,
- Cartoon and Tube modes because old value five produce asymmetric arrows in Cartoon mode (visual defect).
These changes effects on golden tests results. It is needed to upload new pictures for Tube and Cartoon mode
=> Fix normals

.codeclimate.yml, src/Miew.js, src/VolumeVisual.js, src/gfx/VolumeBounds.js, src/gfx/gfxutils.js, src/settings.js
This functionality helps better to understand the borders of volume density data.
There is a new mesh of segment lines geometry, which is connected to VolumeVisual. This mesh is a frame of origin (experimental) parallelepiped.
To turn off/on the frame it is necessary to command: set modes.VD.frame false/true
By default it is visible.
=> Drawing volume density frame 

demo/scripts/ui/Menu.js
Fix: Selection field information does not refresh if Terminal was used to change selection
For reproduce it:
**Preconditions:**
- Run Miew
- Open Menu
- Select Representations
- Select Selection
- Close Menu
**Actions:**
- Open the Terminal
- Enter and execute: selector "elem N" (or any other valid selector)
- Open Menu
There is "Elem N" in selection field
There is still previous selection string.
=> Fix: Selection field information does not update

demo/scripts/ui/Menu.js
Miew gives an error when display mode/color buttons are used without a representation existed
There are to ways to reproduce this bug:
**Preconditions 1:**
- Run Miew
- Open Menu
- Select Load
- Write something that is not a molecule name. For example "a"
- Press Load button
**Preconditions 1:**
- Run Miew
- Open Menu
- Select Load
- Select electron density file
- Press Load button
**Actions:**
Press "Display mode" or "Display color" button
A warning message or disabled icon
An error occur
=> Fix error when display mode/color buttons are used without a representations

src/gfx/gfxutils.js, src/gfx/meshes/TransformGroup.js
This change fixes part of the problem with fps subsidence in selection.
Meshes with the same geometry now are checked for intersection with the ray only once.
=> Improve raycasting performance

src/Miew.js
Selection notation stays when selection was changed via the Terminal
**Preconditions:**
- Run Miew
- Select any aminoacid with your mouse
- Look at selection notation
- Open the Terminal
- Actions:
- Execute select "residue ala"
The notation vanishes
The notation stays
=> Selection notation stays when selection was changed via the Terminal

src/gfx/geometries/ExtrudedObjectsGeometry.js
Restructure ExtrudedObjectsGeometry class
Fix negative indices appeared in it while drawing cartoons
=> Fix negative indices appeared in cartoons

src/Miew.js
Remove redundant selection notification
**Preconditions:**
- Run Miew
- Open the Terminal
- Enter and execute:
- load 4tnw
- mode bs
- unit 1
- select "name OG1" as og1s
- Observe selection is highlighted and notification message appears
**Actions:**
- Change unit to unit 2
- Observe the notification message is still visible
- Change unit back to unit 1
- Observe the molecule
Notification message vanishes after unit is switched
There is no selection highlighted and notification message is still visible
=> Update selection notification when unit changes

src/gfx/objects/LinesObj.js
Edit error message
**Actions:**
- Run Miew
- Open the Terminal
- Enter and execute: line a.326.c a.327.c
- Read error message: "A.318.CB - Wrong atom format it must be '#CHAIN_NAME.#NUMBER.#ATOM_NAME' (e.g. 'A.38.CO1')"
Univocal message text
"#NUMBER" is kind confusing. Need to clarify, for example, "#RESIDUE_NUMBER"
=> Edit error message

src/Miew.js
Fix SSAO effect problem with disappearing obejcts after switching on and off SSAO. Deleted unnecessary buffer when there is no need in it.
=> Fix SSAO effect problem

src/Miew.js
In some cases in miew on screen additional lines are appeared.
Here this bug is solved by correcting check on existing selections which must to be rendered.
=> Fix issue on appearing additional lines on screen

src/Miew.js, src/utils.js
There was an issue when taking screenshots by "screenshot" terminal command in Safari web browser, it results in vertically inverted image. The problem is caused by the bug in Safari
If the Safari bug is fixed by Apple, proposed solution will still work as expected
=> Fix screenshot inverting in Safari

src/Miew.js
The issue was about HI-DPI/Retina devices. The screenshot taken by the internal miew command was different from what was expected. This is due to the fact that the screen buffer size was multiplied by the devicePixelRatio parameter in some functions and then compressed to the requested one. 
The parameter had been set in renderer initialization and never changed later. The solution to the problem was to set the pixel ratio renderer parameter to 1 before rendering frame in screenshot function and then return it the original value. In this case, no unwanted multiplication will occur anywhere.
=> Fix screenshots size on HI-DPI and Retina devices

src/Miew.js, src/gfx/Representation.js, src/gfx/shaders/AO.frag, src/gfx/shaders/Uber.frag, src/gfx/shaders/UberMaterial.js
Now in G buffer for storing normals are used only 3 float numbers from 4. The last one can be used for front/back face flag. As result we have flip define only for lighting and we escape nesseserity to store two normal textures: simple and flipped (such can appear later with new graphic effects)
=> Store front/back face flag in G-buffer

src/Miew.js, src/gfx/shaders/Outline.frag, src/gfx/shaders/OutlineMaterial.js, src/settings.js
This pull requests allows you to adjust the outline thickness through the `outline.thickness` setting.
Attached screenshots demonstrate different thickness settings.
- the default is `1`, the same as it was before, so this shouldn't break anything that already exists
_(Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code)_
=> Add outline thickness setting

src/Miew.js
Fix appearing error in miew on setting value of shadow.on to number
=> Fix situation when shadow.on is set by number

demo/scripts/ui/Menu.js, examples/sequence.html, src/Miew.js
Replace onParseDone and onParseError events usage by parsingFinished event
=> Replace onParseDone and onParseError events by parsingFinished

src/Miew.js
Fix
- It is possible to set zSprites=true when the hardware doesn't support them
- Ambient occlusion breaks in IE11
=> Fix possibility of setting unsupported effects

package.json, packages/lib/package.json, packages/lib/src/Miew.js, packages/lib/src/io/loaders/FileLoader.js, packages/lib/src/io/loaders/FileLoader.test.js, packages/lib/src/io/loaders/Loader.js, packages/lib/src/io/loaders/XHRLoader.js, packages/lib/src/io/loaders/XHRLoader.test.js, packages/lib/src/io/parsers/CCP4Parser.js, packages/lib/src/utils.js, yarn.lock
New features:
1. Upload (.map)s from EMD databank with EMD id and keyword "map", for example: "map: 2222"
2. Upload any volume map (.dsn6 or .map) with pdb id, if such exists; keywords "v" or "volume", for example: "volume: 3jck"
3. Upload files in .gz (compressed) format
=> Add volume maps upload from keyword and id

packages/miew/src/gfx/shaders/UberMaterial.js
Fixes #417
Revert (inadvertent?) changes to UberMaterial added in ba59b112df0a6ae0d8ce2c5de214d2499f3063f7 (#342, #344).
We can introduce some of them back after thorough consideration.
=> Fix the crash while displaying volumetric data

CONTRIBUTING.md
We decided to change the guideline a little. And the decisions are reflected in the document:
- A developer cannot commit or push to the `main` branch anymore. We work using PR.
- Every PR should be approved before being merged into the `main` branch.
- We practice "Squash&merge" approach for that. 
Also, I updated the default branch name (`master`->`main`) due to a recent branch change.
Unfortunately, I didn't update a part with building instructions.
=> Update contributing guidelines with new rules

packages/lib/docs/tutorials/embed.md
A part of #449: fix the outdated instructions on embedding miew in your application using different frameworks. Also, pins the miew version to 0.9.0 for reproducible behavior.
The extraneous startup option `container` is removed to simplify the examples.
- Documentation fix
=> Update and simplify docs on embedding miew

packages/lib/examples/sequence.html
Closes #454
Add a colored border at the bottom of each residue name. The change demonstrates how to access representation parameters (and the Colorer in particular). For the sake of simplicity, only the current Representation is used for all residues. A more correct implementation should iterate over all representations and test if the residue belongs to the corresponding Selector.
=> Color residue names in the "sequence" example

README.md
I noticed that our build status badge points to the "master" branch while we are using the "main" branch instead. Other badges don't work because corresponding integrations are disabled. I fixed the branch reference, removed non-working badges, and added a couple of basic badges that make sense (npm version, downloads counter, and license).
=> Remove outdated badges and add basic ones

.github/PULL_REQUEST_TEMPLATE.md
Changed the wording in the template to cover more cases and encourage toggling all five checkboxes.
=> Clarify the GitHub PR Template we use

packages/app/src/components/App.jsx
Removed code dependency. #487 
The CSS import isn't needed anymore.
note: I didn't find any other dependencies in the code.
_(Put an `x` in the boxes that apply---ideally, all five. If you're unsure about any of them, don't hesitate to ask. We're here to help!)_
=> Remove css dependency from lib

packages/lib/package.json, yarn.lock
Closes https://github.com/epam/miew/security/dependabot/81 by update flat to 5.0.2
=> Bump mocha version to 10.3.0

packages/lib/package.json
- after recent 'rimraf' version update accepted path format changed. now we have to use '--glob' for paths containing wildcard. 
=> Fix test:e2e script for 'lib' package

.github/workflows/ci.yml
Update to actions/setup-node@v4 as previous one is deprecated.
The warning was 
=> Update to actions/setup-node@v4 as previous one is deprecated

packages/app/src/components/menu/panelslist/panels/InfoPanel.jsx
#514 
- Added checking of molecule title provided with metadata
- If there is no title in file metadata we don't try to show it in the panel
=> Fix Panel opening after Serotonin loading

packages/miew-app/src/components/menu/panelslist/panels/GalleryPanel.jsx, packages/miew/demo/menu.html, packages/miew/docs/Thumbnails.md, packages/miew/docs/getting-started-for-dummies.md, packages/miew/docs/tutorials/url.md, packages/miew/examples/api.html, packages/miew/examples/api.js, packages/miew/examples/events.html, packages/miew/examples/events.js, packages/miew/examples/multiple.html, packages/miew/src/Miew.js, packages/miew/src/options.test.js, packages/miew/tools/fetch.py
Resolves #539 
As of July 2, 2024, RCSB PDB no longer serves PDB data in the MMTF compression format. So, this PR:
- Changes the Gallery and examples to use CIF instead of MMTF,
- Removes the "mmtf:" prefix support from the load function,
- Keeps the MMTF file format support for backward compatibility.
Note that the external source ceased to work, so we shouldn't mark it as a breaking change even if it removes the old (non-working) functionality.
=> Use CIF format instead of discontinued MMTF

packages/miew/demo/scripts/ui/Menu.js, packages/miew/src/Miew.js
Resolves #534 
- Move "S" key processing to the demo app (nobody needs it in the library),
- Require "Alt" key with numpad Plus/Minus (a kind of a breaking change but not documented and not used a lot),
- Process editing keys only when editing (an additional safety measure),
- Use `event.code` instead of deprecated `keyCode`.
The `Alt+NumPlus`, `Alt+NumMinus` will still be processed in the miew library unless `miew.enableHotKeys(false)` is called. I believe that's enough to solve the issue in most cases.
- Breaking change (fix or feature that would cause existing functionality not to work as expected)
=> Make it harder to steal character keys from the outer app

packages/miew/demo/scripts/ui/Menu.js, packages/miew/src/Miew.js, packages/miew/src/ui/ObjectControls.js, packages/miew/src/utils/getTopWindow.js, packages/miew/src/utils/getTopWindow.test.js
Resolves #524 
Fixes Uncaught DOMException: Failed to read a named property 'addEventListener' from 'Window': Blocked a frame with origin "xxx" from accessing a cross-origin frame.
=> Access the top window in a safe manner

package.json, yarn.lock
Fix `express` version. This allows to fix corresponding alerts in:
-  `path-to-regexp` https://github.com/epam/miew/security/dependabot/164 
- `body-parser` https://github.com/epam/miew/security/dependabot/168
- `express` as is https://github.com/epam/miew/security/dependabot/167
- `send` https://github.com/epam/miew/security/dependabot/166
- `serve-static` https://github.com/epam/miew/security/dependabot/165
=> Fix express version to close several alerts

packages/miew-react/package.json, yarn.lock
- Update react to 19.1.1 in miew-react
- Update peer dependencies, so miew-react can be used in applications with react 18.2 and upper
=> Update miew-react to use react 19
