epam/miew

src/Miew.js, src/settings.js
Added separate fog color. It's avaliable to change fog color using terminal or disable this option. 
Fog color is a new feature.
Tests e2e weren't passed due to different size of screenshots.
=> Add fog color

src/Miew.js, src/utils/MiewCLIParser.jison, src/utils/MiewCLIParser.js
Added function that represents molecule in Molecule of Month style. It's possible to call function "motm" using terminal.
Molecule of Month style is a new feature.
Tests e2e were passed.
=> Add Molecule of the Month style

src/Miew.js, src/gfx/Representation.js, src/gfx/gfxutils.js, src/gfx/meshes/UberObject.js, src/gfx/meshes/ZClippedMesh.js, src/gfx/meshes/ZSpriteMesh.js, src/gfx/shaders/UberMaterial.js, src/gfx/shaders/Uber_frag.glsl, src/gfx/shaders/Uber_vert.glsl
Unfinished work to be finished later.
=> Add shadowmaps PoC

demo/scripts/ui/Menu.js, src/Miew.js
Issue: Open miew, change background color from Terminal (set bg.color 0xFFFFFF), then get URL. This URL contains the correct background color value but it when loaded the background is the default dark gray.
Has been tested by npm run ci test
=> Fix issue: Background color is not restored from URL.

package.json, yarn.lock
The PR #101 build failed but the newer version seems to be ok. Let's update it via this branch and close #101.
=> Update rollup to the version 1.1.0

src/Miew.js, src/gfx/shaders/Uber_frag.glsl, src/gfx/shaders/Uber_vert.glsl
Implement smart bias in shadows to avoid selfshadowing
=> Implement smart bias in shadows to avoid selfshadowing

src/ComplexVisual.js, src/Miew.js, src/gfx/Representation.js, src/gfx/gfxutils.js
Avoid geometry rebuilding when turn on/off the shadows
and
Fix that rendering does not called if "outline" parameters changing
=> Avoid geometry rebuilding

src/gfx/shaders/UberMaterial.js, src/gfx/shaders/Uber_frag.glsl
Delete unroll_loop in Uber_frag (it caused warnings)
=> Delete unroll_loop in Uber_frag

src/Miew.js
=> Clamp fogAlpha to [0,1]

src/Miew.js, src/gfx/ViewInterpolator.js
Add resetting of viewInterpolator on every molecule loading
=> Reset view interpolator on load

src/Miew.js, src/VolumeVisual.js, src/gfx/VolumeFarPlane.js, src/gfx/geometries/IsoSurface.js, src/gfx/meshes/ZClippedMesh.js
These changes resolve next "todo" or "fixme" issues:
- Added correct handling case if the browser doesn`t support WebGL
- Created a custom plane for Volume Visual
- Made correct floating numbers comparison in IsoSurface
- Remove repeated creation of 'new' vectors/matrices in ZClippedMesh
=> Fix four "todo" and "fixme" issues

demo/scripts/ui/Menu.js, src/Miew-cli.js, src/Miew.js
There was a problem in the case when one tried to add representation when there is no data (no complex visuals)
=> Fix miew crash with adding representation without data

src/Miew.js
Solved problem with incorrect discarding changes in edit component mode.
=> Fix bug with incorrect discard behavior in component mode

src/chem/Complex.js
Resolve CodeClimate issue with code duplication in joinComplexes. Add  simple processing procedure and some docs.
- Refactor
=> Resolve CodeClimate issue with code duplication in joinComplexes

src/gfx/shaders/Uber.vert
SSAO worked incorrect in trace mode.
It used wrong object normals
=> Fix SSAO for trace mode

src/settings.test.js, src/utils/logger.js, src/utils/logger.test.js
Unit tests: 
-  for "logger.js" developed
-  for "settings.js" created
=> Added Unit tests for "logger.js" & "settings.js"

src/gfx/VolumeMesh.js, src/gfx/geometries/ChunkedObjectsGeometry.js, src/gfx/geometries/CylinderBufferGeometry.js, src/gfx/geometries/ExtrudedObjectsGeometry.js, src/gfx/geometries/Instanced2CCylindersGeometry.js, src/gfx/geometries/InstancedSpheresGeometry.js, src/gfx/geometries/IsoSurface.js, src/gfx/geometries/SSIsosurfaceGeometry.js, src/gfx/geometries/ThickLinesGeometry.js, src/gfx/geometries/ThinLinesGeometry.js, src/gfx/geometries/VolumeSurfaceGeometry.js
Change addAttribute function on setAttribute to avoid warnings
=> Fix warnings caused by addAttribute function

examples/miew_via_react/App.js, examples/miew_via_react/controls/ChangeRepOptButton.js
Add new button to miew_via_react
This button changes the mode of rep0 on BS
=> Add change rep mode button to miew_via_react

src/Miew.js, src/ui/ObjectControls.js
Review objectControls events and fix problems with them
=> Fix object controls events

src/ui/ObjectControls.js
- Avoid extra new object creations
- Avoid extra new object cloning
- Rewrite functions to do not returning objects which were created in them
=> Avoid unnecessary new object creations

demo/scripts/ui/Menu.js, examples/sequence.html, src/Miew.js
Rename loading events:
- ...Finished -> ...Done
- parse, load, rebuild -> ...ing
Add new events: fetching, loadingDone, buildingDone
=> Fix loading events

demo/scripts/ui/Menu.js, src/Miew.js
Add new events
- exporting
- exportingDone
Add title changing when 'exporting' receive and after finishing exporting
=> Add export events

src/ComplexVisual.js, src/Miew.js
Add dispatching follow events:
- repAdded - after each representation adding
- repChanged - after each representation changing
- repRemoved - after each representation removing
Deprecate repAdd event
=> Refactor rep events

src/ComplexVisual.js, src/Miew.js, src/gfx/Representation.js
Make ComplexVisual.rep() more clear.
Extrude part of it into representation.js
=> Refactor ComplexVisual.rep function

src/Miew.js, src/gfx/Representation.js, src/gfx/gfxutils.js
Base Miew own shadows (without zSprites and lines)
=> Miew shadows

package.json, yarn.lock
Update webpack to a version 4.42.1
- [ x] I have read [CONTRIBUTING](https://github.com/epam/miew/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/epam/miew/blob/master/CODE_OF_CONDUCT.md) guides.
- [x ] I have followed the code style of this project.
- [x ] I have run `yarn run ci`: lint and tests pass locally with my changes.
=> Greenkeeper/webpack 4.42.1

packages/lib/src/ComplexVisual.js, packages/lib/src/Miew.js, packages/lib/src/gfx/Representation.js, packages/lib/src/gfx/gfxutils.js, packages/lib/src/gfx/meshutils.js, packages/lib/src/gfx/objects/LinesObj.js
Reorganaize processMaterial functions
Solve codeclimat issue (more than 500 lines)
=> Reorganaize processMaterial functions in gfxutils

packages/lib/src/gfx/colorers/Colorer.test.js
=> Add unit tests for colorer.js

packages/lib/src/gfx/colorers/CarbonColorer.test.js, packages/lib/src/gfx/colorers/MoleuleColorer.test.js, packages/lib/src/gfx/colorers/SecondaryStructureColorer.test.js
Add unit tests for the following colorers:
- CarbonColorer.js
- SecondaryStructureColorer.js
- MoleculeColorer.js
=> Test next part colorers

packages/app/package.json, packages/app/src/components/menu/Menu.jsx, packages/app/src/components/menu/terminal/Terminal.jsx, packages/app/src/components/menu/terminal/Terminal.scss, packages/app/src/components/viewer/MiewViewer.jsx, packages/app/src/containers/MenuContainer.js, packages/app/src/containers/TerminalContainer.js, yarn.lock
=> Add terminal

tools/templates/getting-started-for-dummies.md
- Motivation: The project is an open source project, so all documents should be provided in English from Russian
- Change: Only `getting-started-for-dummies` is translated using DeepL, Google Translate, Grammarly
=> Translate help document to English

.appveyor.yml, .travis.yml, package.json, packages/app/package.json, packages/app/webpack.config.js, packages/lib/package.json, packages/lib/rollup.config.js, packages/lib/tools/version.js, packages/lib/webpack.config.js, yarn.lock
Migration to node 18
Configuration changes.
=> 447 bump node to version 18

packages/lib/README.md
See #458 - it seems we have another README with another set of badges that I've missed previously.
=> Remove outdated badges and add basic ones for lib

packages/lib/package.json, yarn.lock
This PR contains commits cherry-picked from #424, #425, #426, #427, #429. I expect them to be closed automatically when this one is merged. If not, I will help them to close.
These are fixes for known security issues.
The dependabot will continue creating PRs to the repository. I expect more fixes from him soon.
=> Bump dependencies, dependabot as of 2023-02-02

yarn.lock
Another portion of automated fixes for known security issues.
This PR contains commits from #468, #469, #470, #471, #472. I expect them to be closed automatically when this one is merged. If not, I will help them to close.
=> Bump dependencies, dependabot as of 2023-09-20

yarn.lock
One more portion of automated fixes for known security issues.
This PR contains commits from #476, #477, #478, #479, #480, #481. I expect them to be closed automatically when this one is merged. If not, I will help them to close.
=> Bump dependencies, dependabot as of 2023-09-21

packages/app/__mocks__/styleMock.js, packages/app/jest.config.js, packages/app/package.json
Bug fix (non-breaking change that fixes an issue)
=> Tests are broken in the react app

package.json, yarn.lock
'underscore' version update to fix critical vulnerability https://github.com/epam/miew/security/dependabot/33
https://stackoverflow.com/a/72946008
=> Update and fix underscore version to 1.13.0

LICENSE.md, README.md, packages/app/src/components/menu/panelslist/panels/AboutPanel.jsx, packages/app/src/components/menu/terminal/Terminal.jsx, packages/lib/README.md, packages/lib/demo/menu.html, packages/lib/demo/scripts/ui/Menu.js, packages/lib/docs/getting-started-for-dummies.md, packages/lib/examples/grid.html, packages/lib/examples/terminal.js, packages/lib/src/io/exporters/fbx/FBXResult.js
#512 
Update a year in copyright from 2015-2023 to 2015-2024.
=> Update years in copyright

.github/workflows/ci.yml
Fix coveralls command in ci.yaml workflow file
Issue: #573 
=> Fix coveralls command in workflow file

.appveyor.yml, .github/workflows/ci.yml, Dockerfile, package.json, packages/miew/package.json, yarn.lock
- Add node 22 and drop node 18
- Update chai-as-promised to 8.0.1 (unblocked as node 18 was drop)
_(Put an `x` in the boxes that apply---ideally, all five. If you're unsure about any of them, don't hesitate to ask. We're here to help!)_
=> Add node 22 and drop node 18
